/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.kotlin-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}


dependencies{
    implementation("jakarta.annotation:jakarta.annotation-api:3.0.0")
    implementation("org.slf4j:slf4j-api:2.0.19")
}