/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm")

    // all-open for Spring stereotypes: Kotlin classes are final by default, which breaks
    // the CGLIB proxies Spring creates for @Configuration, @Scheduled, @Transactional, ...
    id("org.jetbrains.kotlin.plugin.spring")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Type-safe `libs.` accessors are not generated inside precompiled script plugins,
// so the version catalog is looked up explicitly.
val libs = extensions.getByType<VersionCatalogsExtension>().named("libs")

dependencies {
    // Spring Boot's BOM, as a Gradle platform rather than via io.spring.dependency-management:
    // a platform contributes *constraints*, which raise a version but never lower it. The BOM
    // pins kotlin 2.3.21 while this build compiles with 2.4.0, and dependency-management would
    // force the stdlib back down to 2.3.21 under a newer compiler.
    val springBootBom = platform(libs.findLibrary("spring-boot-dependencies").get())
    implementation(springBootBom)
    testImplementation(springBootBom)

    // Shared HTML parser, available to every module.
    implementation(libs.findLibrary("org-jsoup").get())

    // Use JUnit Jupiter for testing. Version comes from the Spring Boot BOM.
    testImplementation("org.junit.jupiter:junit-jupiter")

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
