/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Support convention plugins written in Kotlin. Convention plugins are build scripts in 'src/main' that automatically become available as plugins in the main build.
    `kotlin-dsl`
}

repositories {
    // Use the plugin portal to apply community plugins in convention plugins.
    gradlePluginPortal()
}

dependencies {
    implementation(libs.kotlin.gradle.plugin)

    // Provides the org.jetbrains.kotlin.plugin.spring id (all-open) used by the common conventions.
    implementation(libs.kotlin.allopen)

    // Provides the org.springframework.boot id (bootJar / bootRun).
    implementation(libs.spring.boot.gradle.plugin)
}
